### ISSUE TITLE
Inverted hexagrams

### ISSUE THREAD

**Issue by Porges** [qntm/hexagram-encode#1]
I thought it was worth noting that the ‘binary’ sequence that is followed here is vertically inverted from the way it is represented [in traditional sources](https://www.biroco.com/yijing/sequence.htm#shaoyong).

See, for example, the diagram sent from Bouvet to Leibniz, running ䷁, ䷖, …

![](https://leibniz-bouvet.swarthmore.edu/wp-content/uploads/2018/10/woPPTGa.jpg)

It would also be fun to have the ‘King Wen’ sequence available 😉

**Comment by qntm** [comment]
Noted...
